### ISSUE TITLE
replacing ujson

### ISSUE THREAD

**Issue by slav0nic** [Kinto/kinto-redis#227]
`pip install kinto[redis]` is broken now, `ujson` packaged was removed from the latest kinto version but still used in kinto-redis
https://github.com/Kinto/kinto/pull/2737

**Comment by leplatrem** [comment]
Since kinto-redis imports `ujson` directly it should have it in its dependencies.

We can also align it with kinto core with something like `from kinto.core.utils import json` https://github.com/Kinto/kinto/blob/7432a8ec7f49a21a8380f2e9e48ea630f1332561/kinto/core/utils.py#L34
